### ISSUE TITLE
Suggestion: Unregistering from bower, is possible?

### ISSUE THREAD

**Issue by itsjavi** [theblacksmith/bootstrap-colorpicker#5]
Hello Saulo, will it be possible for you to unregister this package from bower so I could register [`bootstrap-colorpicker`](https://github.com/mjolnic/bootstrap-colorpicker) properly. My bootstrap-colorpicker project has around 700 stars and is highly used, currently has around 200 installs per day, but the project has to use another name because in bower which is not the "official" one and is confusing.

You could do it through `bower login` and `bower unregister bootstrap-colorpicker` or following this instructions from bower project: https://github.com/bower/bower/issues/120

Then you could publish it again under another name.

That would be very kind from your part, because then all people using my plugin in their projects won't be confused by the naming anymore and will be able to use the one I already have registered in npm and composer, so it will be named equal in all package managers.

Looking forward to know your decision.
Thanks =)

Javier

**Comment by svallory** [comment]
It's done! I haven't touched this project in years! I'm glad someone is doing it.

**Comment by itsjavi** [comment]
That's very cool! thank you very much :)
